# This file is a template, and might need editing before it works on your project.
image: node:dubnium

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  script:
    - npm i -g yarn gatsby-cli
    - yarn
    - echo "STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> .env.production
    - echo "STRIPE_PUB_KEY=$STRIPE_PUB_KEY" >> .env.production
    - GATSBY_ACTIVE_ENV=production ./node_modules/.bin/gatsby build --prefix-paths
  artifacts:
    paths:
      - public
  only:
    - master

staging:
  environment:
    name: staging
    # url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/index.html"
    url: "https://staging.nalocal512.com/"
  script:
    - npm i -g yarn gatsby-cli
    - yarn
    - echo "TEST_STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY" >> .env.development
    - echo "TEST_STRIPE_PUB_KEY=$STRIPE_PUB_KEY" >> .env.development
    - GATSBY_ACTIVE_ENV=development ./node_modules/.bin/gatsby build --prefix-paths
  stage:
    deploy
  artifacts:
    paths:
      - public
